version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  api:
    build: ./finsaas_app/
    volumes:
      - ./finsaas_app:/app
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=finansaas.settings 
    entrypoint: ["./entrypoint.sh"]

  nginx:
    build: 
      context: ./nginx/
    ports:
      - "80:80"
    volumes:
      - ./finsaas_app/static:/app/static
      - ./finsaas_app/media:/app/media
    depends_on:
      - api

volumes:
  postgres_data:
